### ISSUE TITLE
ROCK_TEST_ENABLED assumes use of rock_testsuite inside of test_directory

### ISSUE THREAD

**Issue by 2maz** [rock-core/base-cmake#20]
Current usage of ROCK_TEST_ENABLED does not account for using rock_testsuite outside of the test/ directory, in those cases the user has to manually set ROCK_TEST_ENABLED to true or linking to boost unit_test_framework might fail.

**Comment by doudou** [comment]
> Current usage of ROCK_TEST_ENABLED does not account for using rock_testsuite outside of the test/ directory

I don't see why we should support non-standard usage of the Rock macros. Most of them do assume a lot of things that can basically be summarized with "you have to stick to the standard Rock layout".
