### ISSUE TITLE
Issue with recent FindBoost.cmake and Rock.cmake

### ISSUE THREAD

**Issue by g-arjones** [rock-core/base-cmake#33]
I think the FindBoost script that was merged in [#32](https://github.com/rock-core/base-cmake/pull/32) (and also the one bundled with cmake > 2.8) may break some rock packages because it doesn't preserve cached values from previous find_package() calls. Rock targets using "DEPS_CMAKE Boost" (see [rock_target_definition()](https://github.com/rock-core/base-cmake/blob/master/modules/Rock.cmake#L318) macro) are likely to be built with boost linker flags missing. 

Simple CMakelists.txt to demo this:

```
cmake_minimum_required(VERSION 2.6)
find_package(Rock)
find_package(Boost REQUIRED COMPONENTS regex)
rock_find_cmake(Boost REQUIRED)
message("-- \${Boost_LIBRARIES} = ${Boost_LIBRARIES}") 
```

Using "old" FindBoost.cmake:

```
arjones@elementary:~/cmake_test/build$ cmake ..
-- ${Boost_LIBRARIES} = /usr/lib/x86_64-linux-gnu/libboost_regex.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/arjones/cmake_test/build
arjones@elementary:~/cmake_test/build$ 
```

Now, using the recent FindBoost.cmake:

```
arjones@elementary:~/cmake_test/build$ cmake ..
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   regex
-- Boost version: 1.58.0
-- ${Boost_LIBRARIES} = 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/arjones/cmake_test/build
arjones@elementary:~/cmake_test/build$ 
```

Note that ${Boost_LIBRARIES} is unset after rock_find_cmake() call.

**Comment by g-arjones** [comment]
Maybe we can implement our own "cache" like [this](https://github.com/rock-core/base-cmake/pull/34)?

**Comment by jmachowinski** [comment]
The correct usage of the FindBoost would be :
    DEPS_PLAIN 
        Boost_SYSTEM Boost_FILESYSTEM Boost_REGEX Boost_THREAD

**Comment by g-arjones** [comment]
There are packages using it like [this](https://github.com/rock-core/perception-frame_helper/blob/master/src/CMakeLists.txt#L27), which was fine before [#32](https://github.com/rock-core/base-cmake/pull/32)...

**Comment by jmachowinski** [comment]
Interesting, frame helper is not linking boost at all.. which is a bug...

I agree, that the findBoost.cmake reacted different before, but using
it in the way that bugs now, looks more like a hack than a normal way to me.
So I would just go with fixing the affected CMakeLists.txt files.

**Comment by g-arjones** [comment]
Fair enough, you may close this issue and the PR I opened if you like.
