### ISSUE TITLE
Generated Makefile with too many parameters

### ISSUE THREAD

**Issue by Rauldg** [rock-core/base-cmake#49]
I am finding this error compiling one package that uses the Cmake macros with Autoproj.

```bash
c++: error trying to exec '/usr/lib/gcc/x86_64-linux-gnu/7/cc1plus': execv: Argument list too long
``` 

I could not yet generate a minimal reproducible case to post here and the code that produces this is internal. Sorry for that.

This is what I could find that looks more similar to what I think is happening: https://stackoverflow.com/questions/43184251/cmake-command-line-too-long-windows

Similar error but triggering on the linking phase: https://gitlab.kitware.com/cmake/cmake/issues/16206

Is there some flag I can set on the CMakeLists that might help producing valid make files? Maybe some setting of Autoproj?

I tried to put this at the end of the CMakeLists but did not help:
```bash
SET(CMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS 1)
SET(CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS 1)

SET(CMAKE_C_RESPONSE_FILE_LINK_FLAG "@")
SET(CMAKE_CXX_RESPONSE_FILE_LINK_FLAG "@")
```

I use Ubuntu 18.04.

**Comment by doudou** [comment]
You could try running make manually in the package's build folder with VERBOSE=1. The problem should be triggered, and you should see the whole line

I am guessing that it is a combination of having a lot of dependencies, and/or very long paths to these dependencies. It might be also that there is an explosion, that is depending on multiple packages, and each package having long (redundant) dependency lists.

**Comment by Rauldg** [comment]
Yes, that is what happens and I can reproduce it as you explained.

@2maz provided me with a modification for [this method](https://github.com/orocos-toolchain/orogen/blob/master/lib/orogen/gen/base.rb#L82) which inserts in the orogen `CMakeLists.txt` commands to remove the duplicated of dependencies and flags. 

I am not sure if that patch is already a final solution to be integrated in the orogen library or there are other options which might be better. 

By the way, I am using the (rock osdeps)[https://github.com/rock-core/rock-osdeps-package_set] and that is partially responsible for the larger size of the includes and flags.

**Comment by doudou** [comment]
@2maz fix merged, I'm closing this. Reopen if the problem persists.
